//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//Signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

// Account Detail
export const GETACCOUNT_REQUEST ='GETACCOUNT_REQUEST';
export const GETACCOUNT_FAILED ='GETACCOUNT_FAILED';
export const GETACCOUNT_RESPONSE ='GETACCOUNT_RESPONSE';

// Get All User Type
export const GETALLUSERTYPE_REQUEST ='GETALLUSERTYPE_REQUEST';
export const GETALLUSERTYPE_RESPONSE ='GETALLUSERTYPE_RESPONSE';
export const GETALLUSERTYPEFAIL_RESPONSE ='GETALLUSERTYPEFAIL_RESPONSE';

// Get Wine type by user type
export const GETWINETYPEBYUSERTYPE_REQUEST ='GETWINETYPEBYUSERTYPE_REQUEST';
export const GETWINETYPEBYUSERTYPE_RESPONSE ='GETWINETYPEBYUSERTYPE_RESPONSE';
export const GETWINETYPEBYUSERTYPEFAIL_RESPONSE ='GETWINETYPEBYUSERTYPEFAIL_RESPONSE';

// Get Wineries by wine type
export const GETWINERIESBYWINETYPE_REQUEST = 'GETWINERIESBYWINETYPE_REQUEST';
export const GETWINERIESBYWINETYPE_RESPONSE = 'GETWINERIESBYWINETYPE_RESPONSE';
export const GETWINERIESBYWINETYPEFAIL_RESPONSE = 'GETWINERIESBYWINETYPEFAIL_RESPONSE';

// Insert tour
export const INSERTTOUR_REQUEST = 'INSERTTOUR_REQUEST';
export const INSERTTOUR_RESPONSE = 'INSERTTOUR_RESPONSE';
export const INSERTTOURFAIL_RESPONSE = 'INSERTTOURFAILE_RESPONSE';

// Get tour by id
export const GETTOURBYID_REQUEST = 'GETTOURBYID_REQUEST';
export const GETTOURBYID_RESPONSE = 'GETTOURBYID_RESPONSE';
export const GETTOURBYIDFAIL_RESPONSE = 'GETTOURBYIDFAIL_RESPONSE';

// Delete tour
export const DELETETOUR_REQUEST = 'DELETETOUR_REQUEST';
export const DELETETOUR_RESPONSE = 'DELETETOUR_RESPONSE';
export const DELETETOURFAIL_RESPONSE = 'DELETETOURFAIL_RESPONSE';

//Forgot Password
export const FORGOTPASSWORD_REQUEST = 'FORGOTPASSWORD_REQUEST';
export const FORGOTPASSWORD_RESPONSE = 'FORGOTPASSWORD_RESPONSE';
export const FORGOTPASSWORD_FAILED = 'FORGOTPASSWORD_FAILED';

// Profile Image
export const LOADPROFILEIMAGE_REQUEST='LOADPROFILEIMAGE_REQUEST';
export const PROFILEIMAGELOADED_RESPONSE = 'PROFILEIMAGELOADED_RESPONSE';
export const FAILEDLOADINGPROFILEIMAGE_RESPONSE = 'FAILEDLOADINGPROFILEIMAGE_RESPONSE';

//UserProfile
export const LOADUSERPROFILE_REQUEST='LOADUSERPROFILE_REQUEST';
export const USERPROFILELOADED_RESPONSE = 'USERPROFILELOADED_RESPONSE';
export const FAILEDLOADINGUSERPROFILE_RESPONSE = 'FAILEDLOADINGUSERPROFILE_RESPONSE';

//Update Personal Details
export const UPDATEPERSONALDETAIL_REQUEST = 'UPDATEPERSONALDETAIL_REQUEST';
export const UPDATEPERSONALDETAIL_RESPONSE = 'UPDATEPERSONALDETAIL_RESPONSE';
export const UPDATEPERSONALDETAILFAILED_RESPONSE = 'UPDATEPERSONALDETAILFAILED_RESPONSE';

//Update Device Token
export const UPDATEDEVICETOKEN_REQUEST = 'UPDATEDEVICETOKEN_REQUEST';
export const UPDATEDEVICETOKEN_RESPONSE = 'UPDATEDEVICETOKEN_RESPONSE';
export const UPDATEDEVICETOKENFAILED_RESPONSE = 'UPDATEDEVICETOKENFAILED_RESPONSE';

//Change Password
export const CHANGEPASSWORD_REQUEST = 'CHANGEPASSWORD_REQUEST';
export const CHANGEPASSWORD_RESPONSE = 'CHANGEPASSWORD_RESPONSE';
export const CHANGEPASSWORDFAILED_RESPONSE = 'CHANGEPASSWORDFAILED_RESPONSE';

// Events
export const GETUPCOMINGEVENTS_REQUEST = 'GETUPCOMINGEVENTS_REQUEST';
export const GETUPCOMINGEVENTS_RESPONSE = 'GETUPCOMINGEVENTS_RESPONSE';
export const GETUPCOMINGEVENTSFAILED_RESPONSE = 'GETUPCOMINGEVENTSFAILED_RESPONSE';

export const GETPASTEVENTS_REQUEST = 'GETPASTEVENTS_REQUEST';
export const GETPASTEVENTS_RESPONSE = 'GETPASTEVENTS_RESPONSE';
export const GETPASTEVENTSFAILED_RESPONSE = 'GETPASTEVENTSFAILED_RESPONSE';

// OTP VERIFY
export const VERIFYOTP_REQUEST='VERIFYOTP_REQUEST';
export const VERIFYOTP_RESPONSE = 'VERIFYOTP_RESPONSE';
export const FAILEDVERIFYOTP_RESPONSE = 'FAILEDVERIFYOTP_RESPONSE';
